#!/usr/bin/env ruby
require 'securerandom'
require 'timeout'
require 'json'

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

GradingJob.try_start_next!
